name: Docker installation

on:
  workflow_dispatch:
    inputs:
      hosts:
        required: true
        type: choice
        description: "Hosts to run the playbook on"
        options:
          - developer
          - docker
          - all
jobs:
  deploy:
    runs-on:
      group: ansible

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}

      - name: Run post provisioning playbook
        uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: docker.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.hosts }}
          tags: all
